name: Miri

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  miri:
    name: "Run Miri"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup

      - name: Test with Miri
        run: cargo miri test
